### ISSUE TITLE
add_argument should be add_argument!

### ISSUE THREAD

**Issue by kescobo** [kmsquire/ArgParse2.jl#8]
Since you're modifying the parser... Just a thought :-)

**Comment by kmsquire** [comment]
That makes sense--thanks for the suggestion!

**Comment by kmsquire** [comment]
Would you like to make a pull request with that change?  (If not, I'll get to it at some point.)

**Comment by kmsquire** [comment]
Closed by #11.  (For right now, `add_argument` still works, with a warning.)

**Comment by kescobo** [comment]
Oh great! I was gonna do it today, but got distracted customizing my terminal... literally all day 🤦‍♀

**Comment by kmsquire** [comment]
No worries—I was procrastinating a little by actually fixing this...
